import { ICON_NAMES } from "constants/constant";
import colors from "assets/themes/colors";

export const chartData = [
    {
        userID: "1",
        amount: 20,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Energy",
        transactionIcon: ICON_NAMES.ENERGY,
        color: colors.secondary.chartColorEight,
    },
    {
        userID: "2",
        amount: 20,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Fitness",
        transactionIcon: ICON_NAMES.FITNESS,
        color: colors.secondary.chartColorEleven,
    },
    {
        userID: "1",
        amount: 20,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Vehicle",
        transactionIcon: ICON_NAMES.CAR,
        color: colors.secondary.chartColorFive,
    },
];

export const generalData = [
    {
        userID: "1",
        amount: 700,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Expense",
        transactionIcon: ICON_NAMES.SENDMONEY,
        color: colors.secondary.chartColorEight,
    },
    {
        userID: "2",
        amount: 300,
        type: "income",
        chooseAccount: "gcash",
        categoryName: "Income",
        transactionIcon: ICON_NAMES.RECEIVEMONEY,
        color: colors.secondary.chartColorNineteen,
    },
];

export const expenseData = [
    {
        userID: "1",
        amount: 50,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Fitness",
        transactionIcon: ICON_NAMES.FITNESS,
        color: colors.secondary.chartColorTen,
    },
    {
        userID: "2",
        amount: 602,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Food",
        transactionIcon: ICON_NAMES.FOOD,
        color: colors.secondary.chartColorEight,
    },
    {
        userID: "3",
        amount: 2987,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Bills",
        transactionIcon: ICON_NAMES.HOME,
        color: colors.secondary.chartColorOne,
    },
    {
        userID: "4",
        amount: 10,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Food",
        transactionIcon: ICON_NAMES.FOOD,
        color: colors.secondary.chartColorFive,
    },
    {
        userID: "5",
        amount: 99,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Bills",
        transactionIcon: ICON_NAMES.HOME,
        color: colors.secondary.chartColorSix,
    },
];

export const transactionData = [
    {
        userID: "3",
        amount: 2000,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Bills",
        transactionIcon: ICON_NAMES.HOME,
        comment: "Meralco Payment",
        commentImg: "",
        color: colors.secondary.chartColorOne,
    },
    {
        userID: "2",
        amount: 300,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Fitness",
        transactionIcon: ICON_NAMES.FITNESS,
        comment: "Gym",
        commentImg: "",
        color: colors.secondary.chartColorEight,
    },
    {
        userID: "1",
        amount: 200,
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Food",
        transactionIcon: ICON_NAMES.FOOD,
        comment: "",
        commentImg: "",
        color: colors.secondary.chartColorNineteen,
    },
];

export const chartDataMulti = [
    { name: "General", data: generalData },
    { name: "expense", data: expenseData },
    { name: "Income", data: chartData },
];

export const Users = [
    {
        firstName: "Jose",
        lastName: "Alexei",
        email: "Jose@gmail.com",
        password: "123123",
        userImg: "",
        userID: "1",
        createdAt: "",
        updatedAt: "",
    },
    {
        firstName: "Nico",
        lastName: "Ignacio",
        email: "Nico@gmail.com",
        password: "321321",
        userImg: "",
        userID: "2",
        createdAt: "",
        updatedAt: "",
    },
    {
        firstName: "Jian",
        lastName: "Parcon",
        email: "Jian@gmail.com",
        password: "qwerty",
        userImg: "",
        userID: "3",
        createdAt: "",
        updatedAt: "",
    },
    {
        firstName: "Karlo",
        lastName: "jose",
        email: "Karlo123@gmail.com",
        password: "54321",
        userImg: "",
        userID: "4",
        createdAt: "",
        updatedAt: "",
    },
    {
        firstName: "James",
        lastName: "Reid",
        email: "James.Reid@gmail.com",
        password: "67890",
        userImg: "",
        userID: "5",
        createdAt: "",
        updatedAt: "",
    },
];
export const categories = [
    //income
    {
        userID: "1",
        type: "income",
        categoryName: "Business",
        categoryIcon: ICON_NAMES.CHARTS,
        categoryColor: colors.secondary.chartColorFour,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "income",
        categoryName: "remittance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: colors.secondary.chartColorEleven,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "income",
        categoryName: "Bills",
        categoryIcon: ICON_NAMES.ENERGY,
        categoryColor: colors.secondary.chartColorNineteen,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "income",
        categoryName: "Fulltime",
        categoryIcon: ICON_NAMES.EDUCATION,
        categoryColor: colors.secondary.chartColorFourteen,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "income",
        categoryName: "Freelance",
        categoryIcon: ICON_NAMES.ADD_PHOTO_V1,
        categoryColor: colors.secondary.chartColorSix,
        createdAt: "",
        updatedAt: "",
    },
    //expenses
    {
        userID: "1",
        type: "expense",
        categoryName: "Food",
        categoryIcon: ICON_NAMES.FOOD,
        categoryColor: colors.secondary.chartColorOne,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "expense",
        categoryName: "Water",
        categoryIcon: ICON_NAMES.WATER,
        categoryColor: colors.secondary.chartColorTen,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "expense",
        categoryName: "Electricity",
        categoryIcon: ICON_NAMES.ENERGY,
        categoryColor: colors.primary.colorFive,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "expense",
        categoryName: "Education",
        categoryIcon: ICON_NAMES.EDUCATION,
        categoryColor: colors.secondary.chartColorEight,
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "1",
        type: "expense",
        categoryName: "health",
        categoryIcon: ICON_NAMES.FITNESS,
        categoryColor: colors.secondary.chartColorThirtyOne,
        createdAt: "",
        updatedAt: "",
    },
    //income Nico
    {
        userID: "2",
        type: "income",
        categoryName: "Business",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "income",
        categoryName: "remittance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "income",
        categoryName: "part-time job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "income",
        categoryName: "fulltime job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "income",
        categoryName: "government assistance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    //expenses Nico
    {
        userID: "2",
        type: "expense",
        categoryName: "Food",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "orange",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "expense",
        categoryName: "Water",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "expense",
        categoryName: "Electricity",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "yellow",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "expense",
        categoryName: "Education",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "2",
        type: "expense",
        categoryName: "health",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    //Jian
    //income
    {
        userID: "3",
        type: "income",
        categoryName: "Business",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "income",
        categoryName: "remittance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "income",
        categoryName: "part-time job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "income",
        categoryName: "fulltime job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "income",
        categoryName: "government assistance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    //Jian
    //expenses
    {
        userID: "3",
        type: "expense",
        categoryName: "Food",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "orange",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "expense",
        categoryName: "Water",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "expense",
        categoryName: "Electricity",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "expense",
        categoryName: "Education",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "3",
        type: "expense",
        categoryName: "health",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo
    //income
    {
        userID: "4",
        type: "income",
        categoryName: "Business",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "yellow",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "income",
        categoryName: "remittance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "income",
        categoryName: "part-time job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "income",
        categoryName: "fulltime job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "income",
        categoryName: "government assistance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo
    //expenses
    {
        userID: "4",
        type: "expense",
        categoryName: "Food",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "yellow",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "expense",
        categoryName: "Water",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "expense",
        categoryName: "Electricity",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "expense",
        categoryName: "Education",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "4",
        type: "expense",
        categoryName: "health",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    //James
    //income
    {
        userID: "5",
        type: "income",
        categoryName: "Business",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "income",
        categoryName: "remittance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "income",
        categoryName: "part-time job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "income",
        categoryName: "fulltime job",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "income",
        categoryName: "government assistance",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "yellow",
        createdAt: "",
        updatedAt: "",
    },
    //James
    //expenses
    {
        userID: "5",
        type: "expense",
        categoryName: "Food",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "orange",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "expense",
        categoryName: "Water",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "blue",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "expense",
        categoryName: "Electricity",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "yellow",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "expense",
        categoryName: "Education",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "green",
        createdAt: "",
        updatedAt: "",
    },
    {
        userID: "5",
        type: "expense",
        categoryName: "health",
        categoryIcon: ICON_NAMES.BANK,
        categoryColor: "red",
        createdAt: "",
        updatedAt: "",
    },
];
export const accounts = [
    //jose
    {
        accountID: "01",
        userID: "1",
        accountName: "wallet",
        accountIcon: "",
        accountColor: "red",
        accountBalance: "5000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "02",
        userID: "1",
        accountName: "bank",
        accountIcon: "",
        accountColor: "white",
        accountBalance: "15000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "03",
        userID: "1",
        accountName: "gcash",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "3000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "04",
        userID: "1",
        accountName: "Paymaya",
        accountIcon: "",
        accountColor: "green",
        accountBalance: "3000",
        createdAt: "",
        updatedAt: "",
    },
    //jose
    //Nico
    {
        accountID: "01",
        userID: "2",
        accountName: "wallet",
        accountIcon: "",
        accountColor: "red",
        accountBalance: "5000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "02",
        userID: "2",
        accountName: "bank1",
        accountIcon: "",
        accountColor: "white",
        accountBalance: "15000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "03",
        userID: "2",
        accountName: "gcash",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "3000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "04",
        userID: "2",
        accountName: "Paymaya",
        accountIcon: "",
        accountColor: "green",
        accountBalance: "3000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "05",
        userID: "2",
        accountName: "bank2",
        accountIcon: "",
        accountColor: "orange",
        accountBalance: "10000",
        createdAt: "",
        updatedAt: "",
    },
    //Nico
    //Jian
    {
        accountID: "01",
        userID: "3",
        accountName: "wallet",
        accountIcon: "",
        accountColor: "yellow",
        accountBalance: "7000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "02",
        userID: "3",
        accountName: "bank",
        accountIcon: "",
        accountColor: "white",
        accountBalance: "200000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "03",
        userID: "3",
        accountName: "gcash",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "60000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "04",
        userID: "3",
        accountName: "Paymaya",
        accountIcon: "",
        accountColor: "green",
        accountBalance: "10000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "05",
        userID: "3",
        accountName: "savings",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "500000",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo
    {
        accountID: "01",
        userID: "4",
        accountName: "wallet",
        accountIcon: "",
        accountColor: "red",
        accountBalance: "5000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "02",
        userID: "4",
        accountName: "bank",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "30000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "03",
        userID: "4",
        accountName: "gcash",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "600",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "04",
        userID: "4",
        accountName: "Paymaya",
        accountIcon: "",
        accountColor: "black",
        accountBalance: "5000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "05",
        userID: "4",
        accountName: "savings",
        accountIcon: "",
        accountColor: "green",
        accountBalance: "80000",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo
    //James
    {
        accountID: "01",
        userID: "5",
        accountName: "wallet",
        accountIcon: "",
        accountColor: "brown",
        accountBalance: "5000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "02",
        userID: "5",
        accountName: "bank",
        accountIcon: "",
        accountColor: "red",
        accountBalance: "30000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "03",
        userID: "5",
        accountName: "gcash",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "600",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "04",
        userID: "5",
        accountName: "savings",
        accountIcon: "",
        accountColor: "green",
        accountBalance: "80000",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo
    //James
    {
        accountID: "01",
        userID: "5",
        accountName: "wallet",
        accountIcon: "",
        accountColor: "brown",
        accountBalance: "5000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "02",
        userID: "5",
        accountName: "bank",
        accountIcon: "",
        accountColor: "red",
        accountBalance: "30000",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "03",
        userID: "5",
        accountName: "gcash",
        accountIcon: "",
        accountColor: "blue",
        accountBalance: "600",
        createdAt: "",
        updatedAt: "",
    },
    {
        accountID: "04",
        userID: "5",
        accountName: "savings",
        accountIcon: "",
        accountColor: "green",
        accountBalance: "80000",
        createdAt: "",
        updatedAt: "",
    },
    //James
];

export const Transactions = [
    //jose
    //jose1
    {
        userID: "1",
        amount: "2000",
        type: "income",
        chooseAccount: "wallet",
        categoryName: "fulltime job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //jose2
    {
        userID: "1",
        amount: "1000",
        type: "income",
        chooseAccount: "bank",
        categoryName: "remittance",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //jose3
    {
        userID: "1",
        amount: "500",
        type: "income",
        chooseAccount: "wallet",
        categoryName: "part-time job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //jose4
    {
        userID: "1",
        amount: "1000",
        type: "income",
        chooseAccount: "wallet",
        categoryName: "remittance",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //jose expenses
    {
        userID: "1",
        amount: "1500",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "health",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jose2
    {
        userID: "1",
        amount: "6000",
        type: "expense",
        chooseAccount: "bank",
        categoryName: "Electricity",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //jose3
    {
        userID: "1",
        amount: "500",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Water",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //jose
    //Nico
    //Nico1
    {
        userID: "2",
        amount: "30000",
        type: "income",
        chooseAccount: "bank1",
        categoryName: "fulltime job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico2
    {
        userID: "2",
        amount: "4000",
        type: "income",
        chooseAccount: "bank1",
        categoryName: "part-time job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico3
    {
        userID: "2",
        amount: "3000",
        type: "income",
        chooseAccount: "bank1",
        categoryName: "part-time job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico expenses
    //Nico1
    {
        userID: "2",
        amount: "1500",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "health",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico2
    {
        userID: "2",
        amount: "9000",
        type: "expense",
        chooseAccount: "bank1",
        categoryName: "Electricity",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico3
    {
        userID: "2",
        amount: "500",
        type: "expense",
        chooseAccount: "bank1",
        categoryName: "Water",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico4
    {
        userID: "2",
        amount: "300",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Food",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Nico
    //Jian income
    //Jian1
    {
        userID: "3",
        amount: "35000",
        type: "income",
        chooseAccount: "",
        categoryName: "Business",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jian2
    {
        userID: "3",
        amount: "27000",
        type: "income",
        chooseAccount: "bank",
        categoryName: "fulltime job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jian3
    {
        userID: "3",
        amount: "5000",
        type: "income",
        chooseAccount: "gcash",
        categoryName: "Business",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jian expenses
    //Jian1
    {
        userID: "3",
        amount: "15000",
        type: "expense",
        chooseAccount: "bank",
        categoryName: "health",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jian2
    {
        userID: "3",
        amount: "10000",
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Electricity",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jian3
    {
        userID: "3",
        amount: "5000",
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Water",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Jian4
    {
        userID: "",
        amount: "800",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Food",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo income
    //Karlo1
    {
        userID: "4",
        amount: "4500",
        type: "income",
        chooseAccount: "",
        categoryName: "Business",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo2
    {
        userID: "4",
        amount: "40000",
        type: "income",
        chooseAccount: "bank",
        categoryName: "fulltime job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo3
    {
        userID: "4",
        amount: "5000",
        type: "income",
        chooseAccount: "gcash",
        categoryName: "Business",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo expenses
    //Karlo1
    {
        userID: "4",
        amount: "800",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "health",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo2
    {
        userID: "4",
        amount: "3000",
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Electricity",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo3
    {
        userID: "4",
        amount: "500",
        type: "expense",
        chooseAccount: "gcash",
        categoryName: "Water",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo4
    {
        userID: "4",
        amount: "5000",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Food",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //Karlo5
    {
        userID: "4",
        amount: "400",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Fitness",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James income
    //James1
    {
        userID: "5",
        amount: "70000",
        type: "income",
        chooseAccount: "",
        categoryName: "Business",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James2
    {
        userID: "5",
        amount: "110000",
        type: "income",
        chooseAccount: "bank",
        categoryName: "fulltime job",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James3
    {
        userID: "5",
        amount: "50000",
        type: "income",
        chooseAccount: "bank",
        categoryName: "Business",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James expenses
    //James1
    {
        userID: "5",
        amount: "8000",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Food",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James2
    {
        userID: "5",
        amount: "6500",
        type: "expense",
        chooseAccount: "bank",
        categoryName: "Electricity",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James3
    {
        userID: "5",
        amount: "500",
        type: "expense",
        chooseAccount: "bank",
        categoryName: "Water",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James4
    {
        userID: "5",
        amount: "5000",
        type: "expense",
        chooseAccount: "wallet",
        categoryName: "Fitness",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
    //James5
    {
        userID: "5",
        amount: "4500",
        type: "expense",
        chooseAccount: "bank",
        categoryName: "health",
        transactionIcon: "",
        comments: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        commentImg: "",
        createdAt: "",
        updatedAt: "",
    },
];

export const trasferLog = [
    //jose
    {
        transferID: "1",
        senderName: "Jose Alexei",
        senderID: "1",
        receiverName: "Nico Ignacio",
        receiverID: "2",
        amount: "300",
        createdAt: "",
        updatedAt: "",
        comment: "pa kiss",
        commentImg: "",
    },
    {
        transferID: "2",
        senderName: "Nico Ignacio",
        senderID: "2",
        receiverName: "Jose Alexei",
        receiverID: "1",
        amount: "300",
        createdAt: "",
        updatedAt: "",
        comment: "kiss kita",
        commentImg: "",
    },
    {
        transferID: "3",
        senderName: "Jose Alexei",
        senderID: "1",
        receiverName: "Jian Parcon",
        receiverID: "3",
        amount: "3000",
        createdAt: "",
        updatedAt: "",
        comment: "utang ko",
        commentImg: "",
    },
    //Nico
    {
        transferID: "4",
        senderName: "Jose Alexei",
        senderID: "1",
        receiverName: "Nico Ignacio",
        receiverID: "2",
        amount: "500",
        createdAt: "",
        updatedAt: "",
        comment: "ang mahal ng bigas",
        commentImg: "",
    },
    {
        transferID: "5",
        senderName: "Nico Ignacio",
        senderID: "2",
        receiverName: "Jose Alexei",
        receiverID: "1",
        amount: "800",
        createdAt: "",
        updatedAt: "",
        comment: "panggas mo baby",
        commentImg: "",
    },
    {
        transferID: "6",
        senderName: "Nico Ignacio",
        senderID: "2",
        receiverName: "Jian Parcon",
        receiverID: "3",
        amount: "1000",
        createdAt: "",
        updatedAt: "",
        comment: "kiss kita",
        commentImg: "",
    },
    //Jian
    {
        transferID: "7",
        senderName: "Jian Parcon",
        senderID: "3",
        receiverName: "Nico Ignacio",
        receiverID: "2",
        amount: "3000",
        createdAt: "",
        updatedAt: "",
        comment: "ez money",
        commentImg: "",
    },
    {
        transferID: "8",
        senderName: "Jian Parcon",
        senderID: "3",
        receiverName: "Jose Alexei",
        receiverID: "1",
        amount: "3000",
        createdAt: "",
        updatedAt: "",
        comment: "ez money",
        commentImg: "",
    },
    //Karlo
    {
        transferID: "9",
        senderName: "Jian Parcon",
        senderID: "3",
        receiverName: "Karlo Jose",
        receiverID: "4",
        amount: "7000",
        createdAt: "",
        updatedAt: "",
        comment: "",
        commentImg: "",
    },
    {
        transferID: "10",
        senderName: "Karlo Jose",
        senderID: "4",
        receiverName: "Jose Alexei",
        receiverID: "1",
        amount: "4000",
        createdAt: "",
        updatedAt: "",
        comment: "credit",
        commentImg: "",
    },
    {
        transferID: "11",
        senderName: "Karlo Jose",
        senderID: "4",
        receiverName: "Nico Ignacio",
        receiverID: "1",
        amount: "100",
        createdAt: "",
        updatedAt: "",
        comment: "pamasko",
        commentImg: "",
    },
    //James
    {
        transferID: "12",
        senderName: "James Reid",
        senderID: "5",
        receiverName: "Karlo Jose",
        receiverID: "4",
        amount: "5000",
        createdAt: "",
        updatedAt: "",
        comment: "",
        commentImg: "",
    },
    {
        transferID: "10",
        senderName: "Karlo Jose",
        senderID: "4",
        receiverName: "James Reid",
        receiverID: "5",
        amount: "4000",
        createdAt: "",
        updatedAt: "",
        comment: "credit",
        commentImg: "",
    },
    {
        transferID: "11",
        senderName: "Karlo Jose",
        senderID: "4",
        receiverName: "James Reid",
        receiverID: "5",
        amount: "100",
        createdAt: "",
        updatedAt: "",
        comment: "pamasko",
        commentImg: "",
    },
];

export const colorCollection = [
    {
        colorID: "1",
        color: "#5FB572",
    },
    {
        colorID: "2",
        color: "#00A3FF",
    },
    {
        colorID: "3",
        color: "#1602FF",
    },
    {
        colorID: "4",
        color: "#FF00D6",
    },
    {
        colorID: "5",
        color: "#8BCA97",
    },
    {
        colorID: "6",
        color: "#76B65F",
    },
    {
        colorID: "7",
        color: "#5FB572",
    },
    {
        colorID: "8",
        color: "#00A3FF",
    },
    {
        colorID: "9",
        color: "#1602FF",
    },
    {
        colorID: "10",
        color: "#FF00D6",
    },
    {
        colorID: "11",
        color: "#8BCA97",
    },
    {
        colorID: "12",
        color: "#76B65F",
    },
    {
        colorID: "13",
        color: "#5FB572",
    },
    {
        colorID: "14",
        color: "#00A3FF",
    },
    {
        colorID: "15",
        color: "#1602FF",
    },
    {
        colorID: "16",
        color: "#FF00D6",
    },
    {
        colorID: "17",
        color: "#8BCA97",
    },
    {
        colorID: "18",
        color: "#76B65F",
    },
];

export const transactionHistoryData = [
    {
        title: "January",
        data: [
            {
                userID: "1",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Energy",
                transactionIcon: ICON_NAMES.ENERGY,
                color: colors.secondary.chartColorEight,
            },
            {
                userID: "2",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Fitness",
                transactionIcon: ICON_NAMES.FITNESS,
                color: colors.secondary.chartColorEleven,
            },
            {
                userID: "1",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Vehicle",
                transactionIcon: ICON_NAMES.CAR,
                color: colors.secondary.chartColorFive,
            },
        ],
    },
    {
        title: "February",
        data: [
            {
                userID: "1",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Energy",
                transactionIcon: ICON_NAMES.ENERGY,
                color: colors.secondary.chartColorEight,
            },
            {
                userID: "2",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Fitness",
                transactionIcon: ICON_NAMES.FITNESS,
                color: colors.secondary.chartColorEleven,
            },
            {
                userID: "1",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Vehicle",
                transactionIcon: ICON_NAMES.CAR,
                color: colors.secondary.chartColorFive,
            },
        ],
    },
    {
        title: "March",
        data: [
            {
                userID: "1",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Energy",
                transactionIcon: ICON_NAMES.ENERGY,
                color: colors.secondary.chartColorEight,
            },
            {
                userID: "2",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Fitness",
                transactionIcon: ICON_NAMES.FITNESS,
                color: colors.secondary.chartColorEleven,
            },
            {
                userID: "1",
                amount: 20,
                type: "expense",
                chooseAccount: "gcash",
                categoryName: "Vehicle",
                transactionIcon: ICON_NAMES.CAR,
                color: colors.secondary.chartColorFive,
            },
        ],
    },
];

export const transferHistoryLogData = [
    {
        title: "January",
        data: [
            {
                senderName: "Gcash",
                receiverName: "Wallet",
                amount: 2000,
            },
            {
                senderName: "Wallet",
                receiverName: "UnionBank",
                amount: 3500,
            },
            {
                senderName: "Wallet",
                receiverName: "Landbank",
                amount: 200,
            },
        ],
    },
    {
        title: "February",
        data: [
            {
                senderName: "Gcash",
                receiverName: "Wallet",
                amount: 2000,
            },
            {
                senderName: "Wallet",
                receiverName: "UnionBank",
                amount: 3500,
            },
            {
                senderName: "Wallet",
                receiverName: "Landbank",
                amount: 200,
            },
        ],
    },
    {
        title: "March",
        data: [
            {
                senderName: "Gcash",
                receiverName: "Wallet",
                amount: 2000,
            },
            {
                senderName: "Wallet",
                receiverName: "UnionBank",
                amount: 3500,
            },
            {
                senderName: "Wallet",
                receiverName: "Landbank",
                amount: 200,
            },
        ],
    },
    {
        title: "April",
        data: [
            {
                senderName: "Gcash",
                receiverName: "Wallet",
                amount: 2000,
            },
            {
                senderName: "Wallet",
                receiverName: "UnionBank",
                amount: 3500,
            },
            {
                senderName: "Wallet",
                receiverName: "Landbank",
                amount: 200,
            },
        ],
    },
];
