export const FONTS = {
    BOLD: "Lato-Bold",
    LIGHT: "Lato-Light",
    REGULAR: "Lato-Regular",
    MEDIUM: "Lato-Medium",
    BLACK: "Lato-Black",
};

// export const ICON_NAMES = {
//     ACCOUNT: "account-icon",
//     ADD: "add-icon",
//     APPLIANCE: "appliances-icon",
// ADD_PHOTO_V1: "add-photo-v1",
// ADD_PHOTO_V2: "add-photo-v2",
// BACK: "back-icon",
//     BANK: "bank-icon",
//     BILLS: "bills-icon",
//     BLENDER: "blender-icon",
//     BUS: "bus-icon",
//     BONUS_MONEY: "bonus-money",
//     BUSINESS: "business-icon",
//     CALCULATOR: "calculator-icon",
// CALENDAR: "calendar-icon",
//     CAR: "car-icon",
//     CAR_REPAIR: "car-repair-icon",
// CATEGORIES: "categories-icon",
// CHARTS: "charts-icon",
//     CLOTHING: "clothing-icon",
// DASHBOARD: "dashboard-icon",
//     DIVIDENDS: "dividends-icon",
// DROPDOWN: "dropdown-icon",
// EDIT: "edit-icon",
//     EDUCATION: "education-icon",
//     ELECTRONICS: "electronics-icon",
//     ENERGY: "energy-icon",
// FILTER: "filter-icon",
//     FITNESS: "fitness-icon",
//     FOOD: "food-icon",
//     FUN_MONEY: "fun-money-icon",
//     GAMING: "gaming-icon",
//     GAS: "gas-icon",
//     GIFT: "gift-icon",
//     GROCERY: "grocery-icon",
//     HEALTH: "health-icon",
// HOME: "home-icon",
//     HOMEDELIVERY: "home-delivery-icon",
//     INSURANCE: "insurance-icon",
//     INTERNET: "internet-icon",
//     INVESTMENT: "investment-icon",
//     JEWELRY: "jewelry-icon",
// LOGOUT: "logout-icon",
//     MAKEUP: "make-up-icon",
// MORE: "more-icon",
//     MOTORCYCLE: "motorcycle-icon",
//     PART_TIME: "part-time-icon",
//     PERSONAL_CARE: "personal-care-icon",
//     PETS: "pets-icon",
//     PHONE_BILL_1: "phone-bill-1-icon",
//     PHONE_BILL_2: "phone-bill-2-icon",
//     SALARY: "salary",
//     SCHOOL_SUPPLIES: "school-supplies-icon",
//     SHOES: "shoes-icon",
//     STORE_BUSINESS: "store-business-icon",
//     STREAMING_SUBSCRIPTION: "streaming-subscription-icon",
//     PLANE: "plane-icon",
//     RECEIVEMONEY: "receive-money-icon",
//     REFRESH: "refresh-icon",
//     SENDMONEY: "send-money-icon",
// SETTINGS: "settings-icon",
//     TRAIN: "train-icon",
// TRANSFER: "transfer-icon",
// USERPROFILE: "user-profile-icon",
//     WATER: "water-icon",
//     WASHING_MACHINE: "washing-machine-icon",
// };

export const ICON_NAMES = {
    SYSTEM_ICONS: {
        ACCOUNT: "account-icon",
        ADD: "add-icon",
        ADD_PHOTO_V1: "add-photo-v1",
        ADD_PHOTO_V2: "add-photo-v2",
        BACK: "back-icon",
        CALENDAR: "calendar-icon",
        CATEGORIES: "categories-icon",
        CHARTS: "charts-icon",
        CROSS: "cross-icon",
        DASHBOARD: "dashboard-icon",
        DROPDOWN: "dropdown-icon",
        EDIT: "edit-icon",
        FILTER: "filter-icon",
        LOGOUT: "logout-icon",
        MORE: "more-icon",
        SETTINGS: "settings-icon",
        TRANSFER: "transfer-icon",
        USERPROFILE: "user-profile-icon",
        EXPENSE: "expense-icon",
        INCOME: "income-icon"
    },
    CATEGORIES_ICONS: {
        APPLIANCE: "appliances-icon",
        BANK: "bank-icon",
        BILLS: "bills-icon",
        BLENDER: "blender-icon",
        BUS: "bus-icon",
        BONUS_MONEY: "bonus-money",
        BUSINESS: "business-icon",
        CALCULATOR: "calculator-icon",
        CAR: "car-icon",
        CAR_REPAIR: "car-repair-icon",
        CLOTHING: "clothing-icon",
        DIVIDENDS: "dividends-icon",
        EDUCATION: "education-icon",
        ELECTRONICS: "electronics-icon",
        ENERGY: "energy-icon",
        FITNESS: "fitness-icon",
        FOOD: "food-icon",
        FUN_MONEY: "fun-money-icon",
        GAMING: "gaming-icon",
        GAS: "gas-icon",
        GIFT: "gift-icon",
        GROCERY: "grocery-icon",
        HEALTH: "health-icon",
        HOME: "home-icon",
        HOMEDELIVERY: "home-delivery-icon",
        INSURANCE: "insurance-icon",
        INTERNET: "internet-icon",
        INVESTMENT: "investment-icon",
        JEWELRY: "jewelry-icon",
        MAKEUP: "make-up-icon",
        MOTORCYCLE: "motorcycle-icon",
        PART_TIME: "part-time-icon",
        PERSONAL_CARE: "personal-care-icon",
        PETS: "pets-icon",
        PHONE_BILL_1: "phone-bill-1-icon",
        PHONE_BILL_2: "phone-bill-2-icon",
        SALARY: "salary",
        SCHOOL_SUPPLIES: "school-supplies-icon",
        SHOES: "shoes-icon",
        STORE_BUSINESS: "store-business-icon",
        STREAMING_SUBSCRIPTION: "streaming-subscription-icon",
        PLANE: "plane-icon",
        RECEIVEMONEY: "receive-money-icon",
        SENDMONEY: "send-money-icon",
        TRAIN: "train-icon",
        TRANSFER: "transfer-icon",
        WATER: "water-icon",
        WASHING_MACHINE: "washing-machine-icon",
    },

};
