export const FONTS = {
    BOLD: "Lato-Bold",
    LIGHT: "Lato-Light",
    REGULAR: "Lato-Regular",
    MEDIUM: "Lato-Medium",
    BLACK: "Lato-Black",
};

export const ICON_NAMES = {
    ACCOUNT: "account-icon",
    ADD: "add-icon",
    ADD_PHOTO_V1: "add-photo-v1",
    ADD_PHOTO_V2: "add-photo-v2",
    BACK: "back-icon",
    BANK: "bank-icon",
    BUS: "bus-icon",
    CALCULATOR: "calculator-icon",
    CALENDAR: "calendar-icon",
    CAR: "car-icon",
    CATEGORIES: "categories-icon",
    CHARTS: "charts-icon",
    DASHBOARD: "dashboard-icon",
    DROPDOWN: "dropdown-icon",
    EDIT: "edit-icon",
    EDUCATION: "education-icon",
    ENERGY: "energy-icon",
    FILTER: "filter-icon",
    FITNESS: "fitness-icon",
    FOOD: "food-icon",
    GROCERY: "grocery-icon",
    HEALT: "healt-icon",
    HOME: "home-icon",
    LOGOUT: "logout-icon",
    MORE: "more-icon",
    PLANE: "plane-icon",
    RECEIVEMONEY: "receive-money-icon",
    REFRESH: "refresh-icon",
    SENDMONEY: "send-money-icon",
    SETTINGS: "settings-icon",
    TRANSFER: "transfer-icon",
    USERPROFILE: "user-profile-icon",
    WATER: "water-icon",
};
