import React from "react";
import PropTypes from "prop-types";
import { ICON_NAMES } from "constants/constant";

import AccountIcon from "assets/icons/AccountIcon";
import AddIcon from "assets/icons/AddIcon";
import Appliance from "assets/icons/ApplianceIcon";
import AddPhotoV1Icon from "assets/icons/AddPhotoV1Icon";
import AddPhotoV2Icon from "assets/icons/AddPhotoV2Icon";
import BankIcon from "assets/icons/BankIcon";
import BackIcon from "assets/icons/BackIcon";
import BillsIcon from "assets/icons/BillsIcon";
import BlenderIcon from "assets/icons/BlenderIcon";
import BonusMoneyIcon from "assets/icons/BonusMoneyIcon";
import BusinessIcon from "assets/icons/BusinessIcon";
import BusIcon from "assets/icons/BusIcon";
import CalculatorIcon from "assets/icons/CalculatorIcon";
import CalendarIcon from "assets/icons/CalendarIcon";
import CarIcon from "assets/icons/CarIcon";
import CarRepairIcon from "assets/icons/CarRepairIcon";
import CategoriesIcon from "assets/icons/CategoriesIcon";
import ChartsIcon from "assets/icons/ChartsIcon";
import ClothingIcon from "assets/icons/ClothingIcon";
import DashboardIcon from "assets/icons/DashboardIcon";
import DividendsIcon from "assets/icons/DividendsIcon";
import DropdownIcon from "assets/icons/DropdownIcon";
import EditIcon from "assets/icons/EditIcon";
import EducationIcon from "assets/icons/EducationIcon";
import EnergyIcon from "assets/icons/EnergyIcon";
import FilterIcon from "assets/icons/FilterIcon";
import FitnessIcon from "assets/icons/FitnessIcon";
import FoodIcon from "assets/icons/FoodIcon";
import GasIcon from "assets/icons/GasIcon";
import GroceryIcon from "assets/icons/GroceryIcon";
import HealthIcon from "assets/icons/HealtIcon";
import HomeIcon from "assets/icons/HomeIcon";
import LogoutIcon from "assets/icons/LogoutIcon";
import MoreIcon from "assets/icons/MoreIcon";
import PlaneIcon from "assets/icons/PlaneIcon";
import ReceiveMoneyIcon from "assets/icons/RecieveMoneyIcon";
import RefreshIcon from "assets/icons/RefreshIcon";
import SendMoneyIcon from "assets/icons/SendMoneyIcon";
import SettingsIcon from "assets/icons/SettingsIcon";
import TransferIcon from "assets/icons/TransferIcon";
import UserProfileIcon from "assets/icons/UserProfileIcon";
import WaterIcon from "assets/icons/WaterIcon";
import ElectronicsIcon from "assets/icons/ElectronicsIcon";
import FunMoneyIcon from "assets/icons/FunMoneyIcon";
import GamingIcon from "assets/icons/Gaming";
import GiftIcon from "assets/icons/GiftIcon";
import HomeDeliveryIcon from "assets/icons/HomeDeliveryIcon";
import InsuranceIcon from "assets/icons/InsuranceIcon";
import InternetIcon from "assets/icons/InternetIcon";
import InsvestmentIcon from "assets/icons/InvestmentsIcon";
import JewelryIcon from "assets/icons/JewelryIcon";
import MakeUpIcon from "assets/icons/MakeUpIcon";
import MotorcycleIcon from "assets/icons/MotorcycleIcon";
import PartTimeIcon from "assets/icons/PartTimeIcon";
import PersonalCareIcon from "assets/icons/PersonalCareIcon";
import PetsIcon from "assets/icons/PetsIcon";
import PhoneBillIcon1 from "assets/icons/PhoneBillIcon1";
import PhoneBillIcon2 from "assets/icons/PhoneBillIcon2";
import SalaryIcon from "assets/icons/SalaryIcon";
import SchoolSuppliesIcon from "assets/icons/SchoolSuppliesIcon";
import ShoesIcon from "assets/icons/ShoesIcon";
import StoreBusinessIcon from "assets/icons/StoreBusinessIcon";
import StreamingSubscriptionIcon from "assets/icons/StreamingSubscriptionIcon";
import TrainIcon from "assets/icons/TrainIcon";
import WashingMachineIcon from "assets/icons/WashingMachineIcon";

const Icon = ({ name, size = 40, color }) => {
    if (name === ICON_NAMES.SYSTEM_ICONS.ACCOUNT) return <AccountIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.ADD) return <AddIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.ADD_PHOTO_V1) return <AddPhotoV1Icon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.ADD_PHOTO_V2) return <AddPhotoV2Icon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.APPLIANCE) return <Appliance color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BANK) return <BankIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BACK) return <BackIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BILLS) return <BillsIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BLENDER) return <BlenderIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BONUS_MONEY) return <BonusMoneyIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BUSINESS) return <BusinessIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.BUS) return <BusIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.CALCULATOR) return <CalculatorIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.CALENDAR) return <CalendarIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.CAR) return <CarIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.CATEGORIES) return <CategoriesIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.CAR_REPAIR) return <CarRepairIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.CHARTS) return <ChartsIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.CLOTHING) return <ClothingIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.DASHBOARD) return <DashboardIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.DIVIDENDS) return <DividendsIcon color={color} size={size} />;
    if (name === ICON_NAMES.DROPDOWN) return <DropdownIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.EDIT) return <EditIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.EDUCATION) return <EducationIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.ELECTRONICS) return <ElectronicsIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.ENERGY) return <EnergyIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.FILTER) return <FilterIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.FITNESS) return <FitnessIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.FOOD) return <FoodIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.FUN_MONEY) return <FunMoneyIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.GAMING) return <GamingIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.GAS) return <GasIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.GIFT) return <GiftIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.GROCERY) return <GroceryIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.HEALTH) return <HealthIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.HOME) return <HomeIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.HOMEDELIVERY) return <HomeDeliveryIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.INSURANCE) return <InsuranceIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.INTERNET) return <InternetIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.INVESTMENT) return <InsvestmentIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.JEWELRY) return <JewelryIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.LOGOUT) return <LogoutIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.MAKEUP) return <MakeUpIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.MOTORCYCLE) return <MotorcycleIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.MORE) return <MoreIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.PART_TIME) return <PartTimeIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.PERSONAL_CARE) return <PersonalCareIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.PETS) return <PetsIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.PHONE_BILL_1) return <PhoneBillIcon1 color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.PHONE_BILL_2) return <PhoneBillIcon2 color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.PLANE) return <PlaneIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.RECEIVEMONEY) return <ReceiveMoneyIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.REFRESH) return <RefreshIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.SALARY) return <SalaryIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.SCHOOL_SUPPLIES) return <SchoolSuppliesIcon color={color} size={size} />; //to change or remove
    if (name === ICON_NAMES.CATEGORIES_ICONS.SHOES) return <ShoesIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.SENDMONEY) return <SendMoneyIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.SETTINGS) return <SettingsIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.STORE_BUSINESS) return <StoreBusinessIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.STREAMING_SUBSCRIPTION) return <StreamingSubscriptionIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.TRAIN) return <TrainIcon color={color} size={size} />;
    if (name === ICON_NAMES.SYSTEM_ICONS.TRANSFER) return <TransferIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.USERPROFILE) return <UserProfileIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.WATER) return <WaterIcon color={color} size={size} />;
    if (name === ICON_NAMES.CATEGORIES_ICONS.WASHING_MACHINE) return <WashingMachineIcon color={color} size={size} />;

    return null;
};

Icon.propTypes = {
    name: PropTypes.string.isRequired,
    color: PropTypes.string.isRequired,
    size: PropTypes.number,
};

export default Icon;
